### ISSUE TITLE
help getting my pool up and running correctly

### ISSUE THREAD

**Issue by ericwilsondc** [EthereumCommonwealth/go-callisto#14]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by ericwilsondc** [comment]
I have geth running and synced, but getting 404 error.  Not sure I have my confs right.

**Comment by ericwilsondc** [comment]
Can anyone help me with my pool setup?

**Comment by yograterol** [comment]
@ericwilsondc which pool software are you using?
