### ISSUE TITLE
Galilei - New functional testnet

### ISSUE THREAD

**Issue by yograterol** [EthereumCommonwealth/go-callisto#27]
With the new HF coming and the addition of Callisto Hub to our ecosystem, Callisto Network will be giving the possibility to create and use dApps over the blockchain more efficiently and comfortably. That is why a brand new functionally testnet environment will be deployed.

### Callisto Testnet (Galilei)

![](https://assets.labroots.com/_public/_files/system/ck/trending/moon-1817885_1280_bb8ce95f4265d92509343ef30b9c3c97.jpg)

Anyone will be able to develop and/or test dApps over Callisto Network using testnet CLO tokens. This feature is essential to ensure that a dApp is correctly working before its official launch/release.

#### Tools available for Galilei

- [ ] Block explorer
- [ ] RPC endpoint
- [ ] Callisto Hub Integration
- [ ] Callisto Wallet integration
- [ ] Galilei documentation

**Comment by Caesaradaka** [comment]
I need a client
