### ISSUE TITLE
How to install the test net?

### ISSUE THREAD

**Issue by charlie-eth** [EthereumCommonwealth/go-callisto#3]
Instructions are empty: https://github.com/EthereumCommonwealth/go-callisto/wiki

**Comment by Methw** [comment]
@calbertuk wait until Testnet 3.0 ready. Genesis of Testnet 2.0 is too big, so it was not recomended.
The wikis will be updated soon.

**Comment by oliverw** [comment]
@Methw Any update on on Testnet 3.0? The rust-callisto node for our test-pool is twiddling thumbs for weeks now, unable to connect to peers 😁

**Comment by Methw** [comment]
@oliverw 
Testnet 3.0 is live. 
Have you pull newest updates?
please try to pass with `--bootnodes` options. use one of these node `enode://afaf655fbc100fec62c292753b8d42eccc4fee246568171549fa97a32196f2419ab6afecc03f251cffdb736df69badd79b7cbaeacdc217d5b194027f6f616aad@45.77.21.21:30303`
`enode://a56ba92bf34da673dfaa756b58f497abc90b4bb1c1b29d5a0e4fb98a8a2f50c683aeb16464e60482478def72273faccc7a4f6093b598bee82a77a677c4550baa@167.99.96.186:30303`
Let me know if you got any errors.

**Comment by oliverw** [comment]
@Methw 

I'm starting parity like this (systemd daemon):

> /usr/local/daemons/parity-clo/target/release/parity --chain galilei --base-path "/data2/clod1" --mode "active" --no-ui --no-dapps --jsonrpc-interface "0.0.0.0" --jsonrpc-threads 4 --no-discovery --allow-ips=public --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --ipc-path "/data2/clod1/geth.ipc" --ipc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --author 0x4d441a184ba7a22551292b8af3506956901a705e --cache-size 512 --logging "info" --log-file "/data2/clod1/debug.log" --jsonrpc-port 8547 --port 30305 --ws-port 18547 --ws-interface all --bootnodes=enode://afaf655fbc100fec62c292753b8d42eccc4fee246568171549fa97a32196f2419ab6afecc03f251cffdb736df69badd79b7cbaeacdc217d5b194027f6f616aad@45.77.21.21:30303,enode://a56ba92bf34da673dfaa756b58f497abc90b4bb1c1b29d5a0e4fb98a8a2f50c683aeb16464e60482478def72273faccc7a4f6093b598bee82a77a677c4550baa@167.99.96.186:30303

Not much is happening tho:

> Mar 26 13:31:40 heimdall parity[27635]: 2018-03-26 13:31:40     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
> Mar 26 13:32:10 heimdall parity[27635]: 2018-03-26 13:32:10     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
> Mar 26 13:32:40 heimdall parity[27635]: 2018-03-26 13:32:40     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
> Mar 26 13:33:10 heimdall parity[27635]: 2018-03-26 13:33:10     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
> Mar 26 13:33:40 heimdall parity[27635]: 2018-03-26 13:33:40     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
> Mar 26 13:34:10 heimdall parity[27635]: 2018-03-26 13:34:10     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
> Mar 26 13:34:40 heimdall parity[27635]: 2018-03-26 13:34:40     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
> Mar 26 13:35:10 heimdall parity[27635]: 2018-03-26 13:35:10     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
> Mar 26 13:35:40 heimdall parity[27635]: 2018-03-26 13:35:40     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
> Mar 26 13:36:10 heimdall parity[27635]: 2018-03-26 13:36:10     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
> Mar 26 13:36:40 heimdall parity[27635]: 2018-03-26 13:36:40     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs
>

**Comment by Methw** [comment]
@oliverw what parity version do you use??
Have you tried to delete your base path before hand??

**Comment by oliverw** [comment]
I'm using https://github.com/EthereumCommonwealth/rust-callisto compiled from source (master branch):

>  version Parity/v1.11.0-unstable-6a61ca356-20180311/x86_64-linux-gnu/rustc1.23.0

I think I did wipe the data folder, but I can try again.

**Comment by Methw** [comment]
@oliverw you could use my repo if you want to compile from the start. With CLO/1.0 branch.
```
git clone https://github.com/Methw/rust-callisto
```

If its not auto connect to peers, try wipe base path folder, and run with bootnodes option like above. The Blockexplorer in https://clo.explorerz.pw and https://explorer.callisto.network use that rust-callisto version.

**Comment by ggramal** [comment]
Hello @Methw about `geth` :smiley:  when i run 
```
./geth --testnet  --verbosity 5 --port 32303
```
In the output i can see this
```
TRACE[03-26|22:32:55] Starting bonding ping/pong               id=1e1d25d9eafd9231 known=false failcount=0 age=422803h32m55.749550371s
TRACE[03-26|22:32:55] New dial task                            task="discovery lookup"
TRACE[03-26|22:32:55] >> FINDNODE/v4                           addr=167.99.96.186:30303 err=nil
TRACE[03-26|22:32:55] >> PING/v4                               addr=167.99.96.186:30303 err=nil
TRACE[03-26|22:32:56] Bumping findnode failure counter         id=1e1d25d9eafd9231 failcount=1
TRACE[03-26|22:32:56] Dial task done                           task="discovery lookup (1 results)"
TRACE[03-26|22:32:56] New dial task                            task="dyndial 1e1d25d9eafd9231 167.99.96.186:30303"
TRACE[03-26|22:32:56] >> FINDNODE/v4                           addr=167.99.96.186:30303 err=nil
TRACE[03-26|22:32:56] New dial task                            task="discovery lookup"
TRACE[03-26|22:32:56] Dial error                               task="dyndial 1e1d25d9eafd9231 167.99.96.186:30303" err="dial tcp 167.99.96.186:30303: getsockopt: connection refused"
TRACE[03-26|22:32:56] Dial task done                           task="dyndial 1e1d25d9eafd9231 167.99.96.186:30303"
TRACE[03-26|22:32:56] Bumping findnode failure counter         id=1e1d25d9eafd9231 failcount=2
TRACE[03-26|22:32:56] >> FINDNODE/v4                           addr=167.99.96.186:30303 err=nil
TRACE[03-26|22:32:57] Bumping findnode failure counter         id=1e1d25d9eafd9231 failcount=3
TRACE[03-26|22:32:57] >> FINDNODE/v4                           addr=167.99.96.186:30303 err=nil
TRACE[03-26|22:32:57] >> PING/v4                               addr=167.99.96.186:30303 err=nil
TRACE[03-26|22:32:57] Bumping findnode failure counter         id=1e1d25d9eafd9231 failcount=4
TRACE[03-26|22:32:57] >> FINDNODE/v4                           addr=167.99.96.186:30303 err=nil
DEBUG[03-26|22:32:57] Removed dead node                        b=14 id=1e1d25d9eafd9231 ip=167.99.96.186
TRACE[03-26|22:32:58] Bumping findnode failure counter         id=1e1d25d9eafd9231 failcount=5
TRACE[03-26|22:32:58] Too many findnode failures, dropping     id=1e1d25d9eafd9231 failcount=5
TRACE[03-26|22:32:59] Starting bonding ping/pong               id=1e1d25d9eafd9231 known=false failcount=5 age=422803h32m59.753149319s
TRACE[03-26|22:32:59] >> PING/v4                               addr=167.99.96.186:30303 err=nil
TRACE[03-26|22:33:00] Dial task done                           task="discovery lookup"
TRACE[03-26|22:33:00] New dial task                            task="discovery lookup"
TRACE[03-26|22:33:03] Starting bonding ping/pong               id=1e1d25d9eafd9231 known=false failcount=5 age=422803h33m3.7533419s
TRACE[03-26|22:33:03] >> PING/v4                               addr=167.99.96.186:30303 err=nil
TRACE[03-26|22:33:04] Dial task done                           task="discovery lookup"
TRACE[03-26|22:33:04] New dial task                            task="discovery lookup"
TRACE[03-26|22:33:07] Starting bonding ping/pong               id=1e1d25d9eafd9231 known=false failcount=5 age=422803h33m7.75356824s
TRACE[03-26|22:33:07] >> PING/v4                               addr=167.99.96.186:30303 err=nil
TRACE[03-26|22:33:08] Dial task done                           task="discovery lookup"
TRACE[03-26|22:33:08] New dial task                            task="discovery lookup"
TRACE[03-26|22:33:11] Starting bonding ping/pong               id=1e1d25d9eafd9231 known=false failcount=5 age=422803h33m11.754102232s
TRACE[03-26|22:33:11] >> PING/v4                               addr=167.99.96.186:30303 err=nil
TRACE[03-26|22:33:12] Dial task done                           task="discovery lookup"
TRACE[03-26|22:33:12] New dial task                            task="discovery lookup"
DEBUG[03-26|22:33:13] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[03-26|22:33:15] Starting bonding ping/pong               id=1e1d25d9eafd9231 known=false failcount=5 age=422803h33m15.753960197s
```
It seems that the node is inaccessible from the network. But thats not true because i can ping it
```
$ ping 167.99.96.186
PING 167.99.96.186 (167.99.96.186) 56(84) bytes of data.
64 bytes from 167.99.96.186: icmp_seq=1 ttl=49 time=202 ms
64 bytes from 167.99.96.186: icmp_seq=2 ttl=49 time=203 ms
64 bytes from 167.99.96.186: icmp_seq=3 ttl=49 time=202 ms
64 bytes from 167.99.96.186: icmp_seq=4 ttl=49 time=203 ms
```

When i execute this
```
./geth --testnet --bootnodes 'enode://afaf655fbc100fec62c292753b8d42eccc4fee246568171549fa97a32196f2419ab6afecc03f251cffdb736df69badd79b7cbaeacdc217d5b194027f6f616aad@45.77.21.21:30303' --verbosity 5 --port 32303
```
The output is different and looks like
```
RACE[03-26|22:52:48] Starting bonding ping/pong               id=afaf655fbc100fec known=false failcount=0 age=422803h52m48.993393558s
TRACE[03-26|22:52:49] >> PING/v4                               addr=45.77.21.21:30303 err=nil
TRACE[03-26|22:52:49] >> FINDNODE/v4                           addr=45.77.21.21:30303 err=nil
TRACE[03-26|22:52:49] << PONG/v4                               addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:49] << NEIGHBORS/v4                          addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:49] << NEIGHBORS/v4                          addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:49] Bumping findnode failure counter         id=afaf655fbc100fec failcount=1
TRACE[03-26|22:52:49] Dial task done                           task="discovery lookup (1 results)"
TRACE[03-26|22:52:49] New dial task                            task="dyndial afaf655fbc100fec 45.77.21.21:30303"
TRACE[03-26|22:52:49] New dial task                            task="discovery lookup"
TRACE[03-26|22:52:49] >> FINDNODE/v4                           addr=45.77.21.21:30303 err=nil
TRACE[03-26|22:52:49] << NEIGHBORS/v4                          addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:49] << NEIGHBORS/v4                          addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:50] Bumping findnode failure counter         id=afaf655fbc100fec failcount=2
TRACE[03-26|22:52:50] >> FINDNODE/v4                           addr=45.77.21.21:30303 err=nil
TRACE[03-26|22:52:50] Failed RLPx handshake                    addr=45.77.21.21:30303 conn=dyndial err=EOF
TRACE[03-26|22:52:50] Setting up connection failed             id=0000000000000000 err=EOF
TRACE[03-26|22:52:50] Dial error                               task="dyndial afaf655fbc100fec 45.77.21.21:30303" err=EOF
TRACE[03-26|22:52:50] Dial task done                           task="dyndial afaf655fbc100fec 45.77.21.21:30303"
TRACE[03-26|22:52:50] << NEIGHBORS/v4                          addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:50] << NEIGHBORS/v4                          addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:50] Bumping findnode failure counter         id=afaf655fbc100fec failcount=3
TRACE[03-26|22:52:50] >> FINDNODE/v4                           addr=45.77.21.21:30303 err=nil
TRACE[03-26|22:52:50] << NEIGHBORS/v4                          addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:50] << NEIGHBORS/v4                          addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:51] Bumping findnode failure counter         id=afaf655fbc100fec failcount=4
TRACE[03-26|22:52:51] >> FINDNODE/v4                           addr=45.77.21.21:30303 err=nil
TRACE[03-26|22:52:51] << NEIGHBORS/v4                          addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:51] << NEIGHBORS/v4                          addr=45.77.21.21:30303 err="unsolicited reply"
TRACE[03-26|22:52:51] Bumping findnode failure counter         id=afaf655fbc100fec failcount=5
TRACE[03-26|22:52:51] Too many findnode failures, dropping     id=afaf655fbc100fec failcount=5
```

**Comment by oliverw** [comment]
@Methw No dice unfortunately. With and without bootnodes.

**Comment by Methw** [comment]
@ggramal @oliverw what are your geth versions? And what branch do you use?? Do we all using CLO/1.0 branch right?

And if you do, maybe try to disable firewall for a moment there.

**Comment by oliverw** [comment]
@Methw  No geth here, parity on branch CLO/1.0.

**Comment by Methw** [comment]
@oliverw go-callisto is geth one. Rust callisto is parity one.
The rust-callisto you used, have you tried with my repos and still got no peers?

Please use `enode://02d6b42905339896bff753d944a7692ed489fd091d695eb7a76026590ba3fd46726bfb817df8687afce42c57af37ec7a62006235e2aae6e6bbcbea097521ac92@45.77.21.21:30303`

I'm updating new node. cc @ggramal

**Comment by ggramal** [comment]
@Methw 
```
~/github/go-callisto$ git branch
* CLO/1.0
```
Version
```
~/github/go-callisto/build/bin$ ./geth version
Geth
Version: 1.8.2-stable
Git Commit: 530d9b378cf524cd28dd4630e4d6e11c69dac92e
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

**Comment by oliverw** [comment]
@Methw Yes, tried with your repo as well. No dice.

**Comment by Methw** [comment]
@ggramal for geth version, try to remove file in .callisto folder, located in ~/.callisto/
`rm -rf ~/.callisto/`

then try run this : 
`./geth --testnet --bootnodes enode://02d6b42905339896bff753d944a7692ed489fd091d695eb7a76026590ba3fd46726bfb817df8687afce42c57af37ec7a62006235e2aae6e6bbcbea097521ac92@45.77.21.21:30303`

@oliverw Use my repo for rust-callisto, compile from fresh clone. Same as before, please try to remove Keys path, db path, path do dapps. Try with this options
 `./parity --chain=galilei --no-ui --no-ws --no-dapps --jsonrpc-apis safe --tracing=on --fat-db=on --pruning=archive --bootnodes enode://02d6b42905339896bff753d944a7692ed489fd091d695eb7a76026590ba3fd46726bfb817df8687afce42c57af37ec7a62006235e2aae6e6bbcbea097521ac92@45.77.21.21:30303,enode://1e1d25d9eafd92319ee85f502c2f5274a62029b3f9ec003cba259a600ae0def256a09ec505a569aabc4a447d2fd4df9c682243091730f83556693dab17206bd0@167.99.96.186:30303 --public-node  --jsonrpc-cors '*' --jsonrpc-hosts all --jsonrpc-interface all`

I was able to build and compile from new installation. already sync now.

Please join discord channel If you still have problems : https://discord.gg/fGdPSA2

**Comment by oliverw** [comment]
@Methw Looks like it was not working because "--fat-db=on" was missing in my systemd script. Can you confirm that warp-sync does not work at the moment?

**Comment by Methw** [comment]
@oliverw I remove --fat-db option. 
` parity --chain=galilei --no-ui --no-ws --no-dapps --jsonrpc-apis safe --bootnodes enode://02d6b42905339896bff753d944a7692ed489fd091d695eb7a76026590ba3fd46726bfb817df8687afce42c57af37ec7a62006235e2aae6e6bbcbea097521ac92@45.77.21.21:30303,enode://1e1d25d9eafd92319ee85f502c2f5274a62029b3f9ec003cba259a600ae0def256a09ec505a569aabc4a447d2fd4df9c682243091730f83556693dab17206bd0@167.99.96.186:30303 --public-node  --jsonrpc-cors '*' --jsonrpc-hosts all --jsonrpc-interface all`

I'm using this, still connect and sync.
but, need to delete base path and all in `~/.local/share/io.parity.ethereum/*` folders first.

**Comment by oliverw** [comment]
@Methw You are right. The difference was the additional bootnodes in your example.

**Comment by ggramal** [comment]
@Methw yep your solution worked 

So this worked for me on Ubuntu 16.04 with go1.9.4 installed

```
$ git clone -b CLO/1.0 https://github.com/EthereumCommonwealth/go-callisto.git
$ cd go-callisto/
$ make geth
$ cd build/bin
$ rm -rf ~/.callisto/*
$ ./geth --testnet --bootnodes enode://02d6b42905339896bff753d944a7692ed489fd091d695eb7a76026590ba3fd46726bfb817df8687afce42c57af37ec7a62006235e2aae6e6bbcbea097521ac92@45.77.21.21:30303
```

**Comment by oliverw** [comment]
@Methw Our test-pool is now up: https://coinfoundry.org/pool/clo

**Comment by Methw** [comment]
@oliverw thanks mate.
I'll share it in discord and tele group.

**Comment by ggramal** [comment]
@Methw One more question how do i compile it on windows 10 :grin:

**Comment by ggramal** [comment]
I have actually managed to get it working on `Windows 10` like this
1) Install docker on  Ubuntu
2) Clone the repository

```
$ git clone -b CLO/1.0 https://github.com/EthereumCommonwealth/go-callisto.git
```
 or update it with `git pull`

3) Run inside the repos folder
```
$ make geth-windows-amd64
```

4) Copy the resulting binary 

```build/bin/geth-windows-4.0-amd64.exe```

 to a windows Machine
5) Open powershell and run 
```
PS C:\> cd PATH/WHERE/YOU/COPIED/THE_BINARY
PS C:\PATH\WHERE\YOU\COPIED\THE_BINARY>.\geth-windows-4.0-amd64.exe --testnet
```
:sunglasses:

**Comment by Methw** [comment]
@ggramal Nice, I make small bash script to automate that process.
check  [This Script](https://github.com/Methw/script)
