### ISSUE TITLE
Release binaries GLIBC

### ISSUE THREAD

**Issue by shrikus** [EthereumCommonwealth/go-callisto#30]
It would be great if the release binaries would target Ubuntu 18.04 or earlier systems.

```
gclo: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by gclo)
```

**Comment by drhashes** [comment]
Latest gclo does not work on ubuntu 16.04 nor 18.04

gclo: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by gclo)

**Comment by DzikNsk** [comment]
deprecated
