### ISSUE TITLE
"Make the go-callisto Windows binary" is not work

### ISSUE THREAD

**Issue by McCalm** [EthereumCommonwealth/go-callisto#31]
#### System information

Windows 10 Enterprise
Build 20H2 19042.1237

#### Golang Version: 

go1.17.1 windows/amd64

#### Source CSv2 Release [Hardfork]; 

go-callisto-1.3.1.zip (Source)

#### Not expected behaviour

Makefile does not work; Fatal: Command arguements too long

--> make geth-windows-amd64

![grafik](https://user-images.githubusercontent.com/78034375/134330552-6a850674-c0bb-4f4f-ad31-ede785b9a24e.png)

**Comment by DzikNsk** [comment]
Windows build available in 2.0.0 releasee
