### ISSUE TITLE
Error: invalid merkle root 

### ISSUE THREAD

**Issue by BBB1331** [EthereumCommonwealth/go-callisto#32]
Hi there,

how to fix it? 
ERROR[06-22|10:45:50.033]
########## BAD BLOCK #########
Chain config: {ChainID: 820 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 20 Constantinople: 3100000 Petersburg: 3100000 Istanbul: 4950000 Muir Glacier: <nil> CLOHF1: 1400000 CLOMP: 2900001, YOLO v1: <nil>, CSv2: 7600000, Engine: ethash}

Number: 8199071
Hash: 0x864ba8139ea949c5cffd65fddc58415663d3896b5fb87d3fd76851b670d6fcd9
         0: cumulative: 66933 gas: 66933 contract: 0xD7D4c85A2B42456Fb5F2F566b5Ed112f8bC5aC56 status: 1 tx: 0x5087f0ecaa12c6cce5ee7d4def5ccda74db50f07d84ef0bb0e60cc43f2897097 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:

Error: invalid merkle root (remote: c4a20d3257dc910353b7ce3eeadee999fbb545ca07d6ac4c8cb7e7062f7bbd11 local: e4a6e9c4f157c581c17390c49f6bf24d7574ea4d66fc0b2a9046668b872efbdd)
##############################

WARN [06-22|10:45:50.035] Synchronisation failed, dropping peer    peer=8e33e9f621144cda err="retrieved hash chain is invalid: invalid merkle root (remote: c4a20d3257dc910353b7ce3eeadee999fbb545ca07d6ac4c8cb7e7062f7bbd11 local: e4a6e9c4f157c581c17390c49f6bf24d7574ea4d66fc0b2a9046668b872efbdd)"

**Comment by mafangtao** [comment]
did you find a solution

**Comment by BBB1331** [comment]
no

**Comment by dkisver1** [comment]
Make sure you're grabbing the latest version.

**Comment by DzikNsk** [comment]
This issue fixed in #37
