### ISSUE TITLE
64bit DAG patch missed in release branch

### ISSUE THREAD

**Issue by shrikus** [EthereumCommonwealth/go-callisto#34]
For some reason commit d990df909d7839640143344e79356754384dcdd0 was not included in the release branch, and after the DAG went over 4GB, the node started rejecting blocks.

**Comment by ghost** [comment]
is this addressed ? My block Submissions are failing for no reason

**Comment by DzikNsk** [comment]
We will work on this after HF, block 16 000 000

**Comment by DzikNsk** [comment]
@shrikus I reviewed the code, this fix already merged, available in 2.0.0 builds, master branch
