### ISSUE TITLE
No peers

### ISSUE THREAD

**Issue by Baal19** [EthereumCommonwealth/go-callisto#35]
Hello, i am trying to run go callisto but it is unable to find any peer.
The firewall is allowing incoming connections do you have any additional peer to add
Thanks!

**Comment by Baal19** [comment]
Hello, after two weeks it is still looking for peers, any update?
Thanks!

**Comment by dkisver1** [comment]
make sure you have --maxpeers set to some number, like --maxpeers 15.

1. I think you need to start:  geth --syncmode "full" --cache=16000 --http --http.addr "127.0.0.1" --http.port 8545 --http.api admin --miner.etherbase "YOURWALLAETADDRESS" --mine --miner.threads=0 --maxpeers 15

2. start the geth console by opening another command shell and type, "geth attach http://127.0.0.1:8545"   

3. Once in the console type: 
admin.addPeer("enode://9360e00de44fd6fd2bdc74146a2040282d7838fe54bb9f345a3fd6caf4571d8942f0c13890f1416822cc4c6905decea1353aae44ec9d989efaa23610aacfb9c6@188.40.111.190:30303")

I am in no way qualified to give this advice, but this works for me.  I hope it helps.

**Comment by Baal19** [comment]
Hello, the bootnode provided works!
Thanks!!!

**Comment by dkisver1** [comment]
I'm glad it worked.  I'm not sure of the root cause of that but I've come across the issue a few times.  Enjoy!

**Comment by Baal19** [comment]
Hello,@dkisver1
my node appears to be synchronized now. May i ask you if your node returns correct block when calling eth_getBlockByNumber("latest") ? The result is always 0 for me but from the node logs i see that it is at the same height as the explorer
