### ISSUE TITLE
Problem with eth_sendTransaction RPC in rust-callisto

### ISSUE THREAD

**Issue by oliverw** [EthereumCommonwealth/go-callisto#5]
First of all, sorry for filing a parity issue here instead of the correct repo. Unfortunately issues are not available on the rust-callisto repo.

Our [Callisto Testpool](https://coinfoundry.org/pool/clo) mined the first block today. When sending the reward to the sole miner responsible for mining the block using eth_sendTransaction, the RPC succeeded but resulted in a transaction that transferred zero value: https://explorer.callisto.network/tx/0xbc41f4a9413674af57f078e8afcd6480510e852472b115444e769de9710b048c. The amount supposed to get transferred can be seen by switching to the "Payments" Tab on the [Pool Page](https://coinfoundry.org/pool/clo). 

This is strange as the transaction was generated by the same code that successfully transferred hundreds of ETH and ETC on our other pools: https://github.com/coinfoundry/miningcore/blob/dev/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs#L451

#### System information

Geth version: rust-callisto compiled from https://github.com/Methw/rust-callisto - branch CLO/1.0
OS & Version: Linux Debian 10.3
Commit hash : HEAD

**Comment by Methw** [comment]
I'll try mining there. But, I think the site is down atm

**Comment by oliverw** [comment]
Sorry, we had some extended website maintenance last night. The pool was totally unaffected.

**Comment by oliverw** [comment]
@Methw Everything's up and miner have mined tons of blocks today. I've also enabled tracing on the parity instance if that helps figuring out what's going on.

**Comment by Methw** [comment]
@oliverw that weird. any log for payment status status?
https://github.com/coinfoundry/miningcore/blob/f7a9751f56650f8d3d64c05bd1f23cc5aee4c5eb/src/MiningCore/Blockchain/Ethereum/EthereumConstants.cs#L23
and are this have impact on payment process?  because atm, maybe you just connected to one peers.

**Comment by oliverw** [comment]
@Methw I've [relaxed](https://github.com/coinfoundry/miningcore/blob/dev/src/MiningCore/Blockchain/Ethereum/EthereumPayoutHandler.cs#L272) the peercount requirement for payouts in the dev branch when using a testnet daemon. So, no that shouldn't make a difference. 

Regarding the payment status, what logging information do you seek?

**Comment by Methw** [comment]
Any errors or warnings from payment process?
if you don't mind, you could insert one of payment process in your mining pool that had zero value here. 

I'm not sure, but are you set gas limit at 940000? I saw other CLO pool with 1/10 gas limit and had no problem with payment. maybe you could try to lower the gas limit to < 100000.

And IF you want to try, you could recompile from [This](https://github.com/EthereumCommonwealth/go-callisto) repo.

PS. I don't know if other pool used the same payment processing method.

**Comment by oliverw** [comment]
Fixed by [35c487d5711efe457cdda0fa67e0254639fa0dae](https://github.com/coinfoundry/miningcore/commit/35c487d5711efe457cdda0fa67e0254639fa0dae)
