### ISSUE TITLE
Makefile recipe for target 'geth' failed

### ISSUE THREAD

**Issue by TheCrowbill** [EthereumCommonwealth/go-callisto#7]
Hi there,

The following issue was encountered while attempting to build a binary executable.
Usage:  `make geth`

#### System information

Geth version: CLO release 1.0 mainnet
OS & Version: Ubuntu Server 16.04,3
Commit hash :  7d6ae16b1a8ace3cf067c6ac47805ce219193efb
Golang version: 1.9

#### Expected behaviour
`make geth` was expected to compile the geth executable

#### Actual behaviour
geth compile failure

#### Steps to reproduce the behaviour
Follows [this](https://github.com/EthereumCommonwealth/go-callisto/wiki/Building-Ethereum) until failure.

#### Backtrace

````
build/env.sh go run build/ci.go install ./cmd/geth
>>> /usr/local/go/bin/go install -ldflags -X main.gitCommit=7d6ae16b1a8ace3cf067c6ac47805ce219193efb -v ./cmd/geth
github.com/EthereumCommonwealth/go-callisto/vendor/gopkg.in/olebedev/go-duktape.v3
# github.com/EthereumCommonwealth/go-callisto/vendor/gopkg.in/olebedev/go-duktape.v3
vendor/gopkg.in/olebedev/go-duktape.v3.duktape.go:133 constant 18446744073709551615 overflows int64
util.go:45: exit status 2
exit status 1
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1
````

**Comment by Methw** [comment]
@TheCrowbill Please update your go version. use go 1.9.2 or up.

I'm make script to install and compile geth.
[check this](https://github.com/Methw/script/blob/master/nodegeth.sh)

**Comment by TheCrowbill** [comment]
@Methw Fixed. Thank you.
